### ISSUE TITLE
error when compile

### ISSUE THREAD

**Issue by intec-id** [suyashm002/watsappp_bot#1]
I've send you email, please help.
I Got message warning when compile
> Configure project :app
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html

**Comment by suyashm002** [comment]
It's only warning it should not be stopping from compile and check your gradle file replace compile with implementation.

**Comment by suyashm002** [comment]
after not getting any followup closing this issue
